name: Deprecated: Deploy to GitHub Pages (disabled)

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: |
          echo "This workflow was disabled because it used deprecated actions (upload-artifact v3)."
          echo "The repository now uses .github/workflows/deploy-gh-pages.yml (peaceiris/actions-gh-pages) for Pages deployment."
